stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
    - data/raw/aichi_temp.csv
    - data/raw/technos_data_23aug_22sept.csv
    - src/preprocess.py
    params:
    - preprocess
    outs:
    - ./data/processed/processed_data.csv
  train:
    cmd: python src/train.py
    deps:
    - data/processed/processed_data.csv
    - params.yaml
    - src/train.py
    outs:
    - models/model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/processed/processed_data.csv
    - models/model.pkl
    - src/evaluate.py
    params:
    - evaluate

  testing:
    cmd: bash -lc 'mkdir -p test_reports && PYTHONPATH=. pytest -q tests | tee 
      test_reports/test_results.txt'
    deps:
    - data/processed/aichi_temperature_forecast.csv
    - data/processed/inference_input_data.csv
    - data/processed/inference_lag_data.csv
    - data/processed/processed_data.csv
    - inference.yaml
    - models/model.pkl
    - params.yaml
    - src
    - tests
    outs:
    - test_reports/test_results.txt
  docker_build:
    cmd: docker build -t technos-forecast:latest .
    deps:
    - docker/entrypoint.sh
    - Dockerfile
    - inference.yaml
    - models/model.pkl
    - params.yaml
    - requirements.infer.txt
    - src
